src/Web/WebMVC/Controllers/ManualCodeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Util.Tools.QrCode.QrCoder;
using WebMVC.Extensions;
using WebMVC.Infrastructure.Services;
using WebMVC.Models.Permissions;
using WebMVC.Models.Queries;
using WebMVC.Models.Roles;
using WebMVC.ViewModels.Json;
using WebMVC.ViewModels.ManualCodeViewModels;

namespace WebMVC.Controllers
{
    [Authorize(Policy = Permissions.Additional.Reviewed)]
    public class ManualCodeController : Controller
    {
        private readonly IQrCodeService _qrCodeService;
        private readonly Util.Tools.QrCode.IQrCodeService _qrCodeGenerator;
        private readonly IPersonalService _personalService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ISystemConfigurationService _systemConfigurationService;

        public ManualCodeController(IQrCodeService qrCodeService, Util.Tools.QrCode.IQrCodeService qrCodeGenerator, IPersonalService personalService, UserManager<ApplicationUser> userManager, ISystemConfigurationService systemConfigurationService)
        {
            _qrCodeService = qrCodeService ?? throw new ArgumentNullException(nameof(qrCodeService));
            _qrCodeGenerator = qrCodeGenerator ?? throw new ArgumentNullException(nameof(qrCodeGenerator));
            _personalService = personalService ?? throw new ArgumentNullException(nameof(personalService));
            _userManager = userManager ?? throw new ArgumentNullException(nameof(userManager));
            _systemConfigurationService = systemConfigurationService ?? throw new ArgumentNullException(nameof(systemConfigurationService));
        }

        [Authorize(Policy = Permissions.QrCodeManagement.Manual.View)]
        public IActionResult Index()
        {
            string userBaseRole = string.Empty;

            if (User.IsInRole(Roles.Manager))
            {
                userBaseRole = Roles.Manager;
            }
            else if (User.IsInRole(Roles.TraderAgent))
            {
                userBaseRole = Roles.TraderAgent;
            }
            else if (User.IsInRole(Roles.Trader))
            {
                userBaseRole = Roles.Trader;
            }

            var getAlipayUserIdQrCode = _qrCodeGenerator.CreateQrCode("https://www.dedemao.com/alipay/authorize.php?scope=auth_base");

            var vm = new IndexViewModel
            {
                UserId = User.GetUserId<string>(),
                UserBaseRole = userBaseRole,
                GetAlipayUserIdQrCodeData= "data:image/png;base64," + Convert.ToBase64String(getAlipayUserIdQrCode)
            };

            return View(vm);
        }




        [Authorize(Policy = Permissions.QrCodeManagement.Manual.View)]
        [HttpPost]
        public async Task<IActionResult> Search([FromForm] KTPagination pagination, [FromForm] KTQuery query, [FromForm] KTSort sort)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index", "QrCode");
            }

            var contextUserId = User.GetUserId<string>();

            var totalItems = await _qrCodeService.GetQrCodeEntrysTotalCount(
                contextUserId,
                query.generalSearch ?? string.Empty,
                QrCodeTypeOption.Manual.Value,
                query.paymentChannel ?? null,
                query.paymentScheme ?? null,
                query.qrCodeStatus ?? null,
                query.pairingStatus ?? null
                );

            var qrCodeEntries = await _qrCodeService.GetQrCodeEntrys(
                pagination.page - 1,
                pagination.perpage,
                contextUserId,
                query.generalSearch ?? string.Empty,
                sort.field,
                QrCodeTypeOption.Manual.Value,
                query.paymentChannel ?? null,
                query.paymentScheme ?? null,
                query.qrCodeStatus ?? null,
                query.pairingStatus ?? null,
                sort.sort);

            var jsonResult = new KTDatatableResult<QrCodeEntry>
            {
                meta = new KTPagination
                {
                    page = pagination.page,
                    pages = (int)Math.Ceiling(((decimal)totalItems / pagination.perpage)),
                    perpage = pagination.perpage,
                    total = totalItems,
                    sort = "desc",
                    field = "QrCodeId"
                },
                data = qrCodeEntries
            };

            return Json(jsonResult);
        }


        [Authorize(Policy = Permissions.QrCodeManagement.Manual.PendingReview.View)]
        [HttpGet]
        public IActionResult PendingReview()
        {
            string userBaseRole = string.Empty;

            if (User.IsInRole(Roles.Manager))
            {
                userBaseRole = Roles.Manager;
            }
            else if (User.IsInRole(Roles.TraderAgent))
            {
                userBaseRole = Roles.TraderAgent;
            }
            else if (User.IsInRole(Roles.Trader))
            {
                userBaseRole = Roles.Trader;
            }

            var vm = new IndexViewModel
            {
                UserId = User.GetUserId<string>(),
                UserBaseRole = userBaseRole
            };

            return View(vm);
        }


        [Authorize(Policy = Permissions.QrCodeManagement.Manual.PendingReview.View)]
        [HttpPost]
        public async Task<IActionResult> PendingReview([FromForm] KTPagination pagination, [FromForm] KTQuery query, [FromForm] KTSort sort)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index", "PendingReview");
            }

            var contextUserId = User.GetUserId<string>();

            var totalItems = await _qrCodeService.GetPendingQrCodeEntrysTotalCount(
                contextUserId,
                query.generalSearch ?? string.Empty,
                QrCodeTypeOption.Manual.Value,
                query.paymentChannel ?? null,
                query.paymentScheme ?? null
                );

            var qrCodeEntries = await _qrCodeService.GetPendingQrCodeEntrys(
                pagination.page - 1,
                pagination.perpage,
                contextUserId,
                query.generalSearch ?? string.Empty,
                sort.field,
                QrCodeTypeOption.Manual.Value,
                query.paymentChannel ?? null,
                query.paymentScheme ?? null,
                sort.sort);

            var jsonResult = new KTDatatableResult<QrCodeEntry>
            {
                meta = new KTPagination
                {
                    page = pagination.page,
                    pages = (int)Math.Ceiling(((decimal)totalItems / pagination.perpage)),
                    perpage = pagination.perpage,
                    total = totalItems,
                    sort = "desc",
                    field = "QrCodeId"
                },
                data = qrCodeEntries
            };

            return Json(jsonResult);
        }


        [Authorize(Policy = Permissions.QrCodeManagement.Manual.View)]
        [Authorize(Policy = Permissions.QrCodeManagement.Manual.CodeData.View)]
        // GET: ManualCode/Detail
        public async Task<IActionResult> Detail(int qrCodeId)
        {
            try
            {
                var qrCode = await _qrCodeService.GetQrCode(
                    User.GetUserId<string>(),
                    qrCodeId
                    );

                return Json(qrCode);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }


        [Authorize(Policy = Permissions.QrCodeManagement.Manual.CodeData.View)]
        // GET: ManualCode/BarcodeInfoForManual
        public async Task<IActionResult> BarcodeInfo(int qrCodeId)
        {
            try
            {
                var barcodeInfo = await _qrCodeService.GetBarcodeInfoForManual(
                    User.GetUserId<string>(),
                    qrCodeId
                    );

                return Json(barcodeInfo);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }


        [Authorize(Policy = Permissions.QrCodeManagement.Manual.CodeData.View)]
        // GET: ManualCode/MerchantInfo
        public async Task<IActionResult> MerchantInfo(int qrCodeId)
        {
            try
            {
                var merchantInfo = await _qrCodeService.GetMerchantInfoAsync(
                    User.GetUserId<string>(),
                    qrCodeId
                    );

                return Json(merchantInfo);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }


        [Authorize(Policy = Permissions.QrCodeManagement.Manual.CodeData.View)]
        // GET: ManualCode/TransactionInfo
        public async Task<IActionResult> TransactionInfo(int qrCodeId)
        {
            try
            {
                var transactionInfo = await _qrCodeService.GetTransactionInfoAsync(
                    User.GetUserId<string>(),
                    qrCodeId
                    );

                return Json(transactionInfo);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }


        [Authorize(Policy = Permissions.QrCodeManagement.Manual.CodeData.View)]
        // GET: ManualCode/BankInfo
        public async Task<IActionResult> BankInfo(int qrCodeId)
        {
            try
            {
                var bankInfo = await _qrCodeService.GetBankInfoAsync(

src/Web/WebMVC/Views/ManualCode/_UpdateBankCodeModal.cshtml
@using WebMVC.Models
<div id="modal__update_bank_qrcode_data" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">更新二维码数据</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                </button>
            </div>
            <div class="modal-body">
                <form id="form_update_bank_qrcode_data" asp-controller="ManualCode" asp-action="UpdateBankCode" class="kt-form" method="post">
                    <div class="form-group">
                        <label for="userId" class="form-control-label">二维码编号 :</label>
                        <input type="text" class="form-control" name="qrcodeid" readonly>
                    </div>
                    <div class="form-group">
                        <label class="">银行名称*</label>
                        <div class="">
                            <select class="form-control kt-select2" id="select_update_bank_bankname" name="bankselect">
                                <option value="">请选择...</option>
                                <option data-bankname="中国工商银行" data-bankmark="ICBC">中国工商银行</option>
                                <option data-bankname="中国建设银行" data-bankmark="CCB">中国建设银行</option>
                                <option data-bankname="汇丰银行" data-bankmark="HSBC">汇丰银行</option>
                                <option data-bankname="中国银行" data-bankmark="BC">中国银行</option>
                                <option data-bankname="中国农业银行" data-bankmark="ABC">中国农业银行</option>
                                <option data-bankname="交通银行" data-bankmark="BC">交通银行</option>
                                <option data-bankname="招商银行" data-bankmark="CMB">招商银行</option>
                                <option data-bankname="中国民生银行" data-bankmark="CMB">中国民生银行</option>
                                <option data-bankname="上海浦东发展银行" data-bankmark="SPDB">上海浦东发展银行</option>
                                <option data-bankname="中国光大银行" data-bankmark="CEB">中国光大银行</option>
                                <option data-bankname="华夏银行" data-bankmark="HB">华夏银行</option>
                                <option data-bankname="广东发展银行" data-bankmark="GDB">广东发展银行</option>
                                <option data-bankname="深圳发展银行" data-bankmark="SDB">深圳发展银行</option>
                                <option data-bankname="兴业银行" data-bankmark="CIB">兴业银行</option>
                                <option data-bankname="国家开发银行" data-bankmark="CDB">国家开发银行</option>
                                <option data-bankname="中国进出口银行" data-bankmark="EIBC">中国进出口银行</option>
                                <option data-bankname="中国农业发展银行" data-bankmark="ADBC">中国农业发展银行</option>
                            </select>
                            <input name="bankname" class="form-control" type="text" placeholder="" hidden>
                            <input name="bankmark" class="form-control" type="text" placeholder="" hidden>

                            <span class="form-text text-muted">选择到账银行。</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="">银行户名*</label>
                        <div class="">
                            <input name="accountname" class="form-control" type="text">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="">银行卡号*</label>
                        <div class="">
                            <input name="cardnumber" class="form-control" type="text">
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-md btn-tall btn-wide kt-font-bold kt-font-transform-u" data-dismiss="modal">取消</button>
                <a href="#" data-action="submit" class="btn btn-success btn-md btn-tall btn-wide kt-font-bold kt-font-transform-u">提交</a>
            </div>
        </div>
    </div>
</div>

src/Web/WebMVC/Views/ManualCode/_UpdateBarcodeModal.cshtml
<div id="modal__update_barcode_qrcode_data" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">更新二维码数据</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                </button>
            </div>
            <div class="modal-body">
                <form id="form_update_barcode_qrcode_data" asp-controller="ManualCode" asp-action="UpdateBarcode" class="kt-form" method="post">
                    <div class="form-group">
                        <label for="userId" class="form-control-label">二维码编号 :</label>
                        <input type="text" class="form-control" name="qrcodeid" readonly>
                    </div>
                    <div class="form-group">
                        <label class="">上传个码*</label>
                        <div class="">
                            <div class="kt-avatar kt-avatar--outline" id="kt_update_barcode_add_qrcode">
                                <div class="kt-avatar__holder" id="kt_update_barcode_qrcode_data" style="background-image: url(assets/media/users/300_10.jpg) "></div>
                                <label class="kt-avatar__upload" data-toggle="kt-tooltip" title="" data-original-title="Change avatar">
                                    <i class="fa fa-pen"></i>
                                    <input type="file" id="kt_update_barcode_qrcode_file_input" name="qrcodefile" accept="image/*">
                                </label>
                                <span class="kt-avatar__cancel" data-toggle="kt-tooltip" title="" data-original-title="Cancel avatar">
                                    <i class="fa fa-times"></i>
                                </span>
                            </div>
                            <input id="kt_update_barcode_qrcode_url" name="qrcodeurl" class="form-control" type="text" readonly>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="">个码金额</label>
                        <input name="amount" class="form-control" type="text" placeholder="若为任意码则留空">
                        <span class="form-text text-muted">若为任意码则留空</span>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-md btn-tall btn-wide kt-font-bold kt-font-transform-u" data-dismiss="modal">取消</button>
                <a href="#" data-action="submit" class="btn btn-success btn-md btn-tall btn-wide kt-font-bold kt-font-transform-u">提交</a>
            </div>
        </div>
    </div>
</div>

src/Web/WebMVC/Views/ManualCode/_UpdateMerchantCodeModal.cshtml
@using WebMVC.Models
<div id="modal__update_merchant_qrcode_data" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">更新二维码数据</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                </button>
            </div>
            <div class="modal-body">
                <form id="form_update_merchant_qrcode_data" asp-controller="ManualCode" asp-action="UpdateMerchantCode" class="kt-form" method="post">
                    <div class="form-group">
                        <label for="userId" class="form-control-label">二维码编号 :</label>
                        <input type="text" class="form-control" name="qrcodeid" readonly>
                    </div>
                    <div class="form-group">
                        <label class="">应用ID</label>
                        <div class="">
                            <input name="appid" class="form-control" type="text" placeholder="">
                            <span class="form-text text-muted"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="">支付宝公钥</label>
                        <div class="">
                            <input name="alipaypublickey" class="form-control" type="text" placeholder="">
                            <span class="form-text text-muted"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="">微信API证书</label>
                        <div>
                            <input name="wechatapicertificate" class="form-control" type="text" placeholder="">
                            <span class="form-text text-muted"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="">私钥</label>
                        <div>
                            <input name="privatekey" class="form-control" type="text" placeholder="">
                            <span class="form-text text-muted"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="">商户ID</label>
                        <div>
                            <input name="merchantid" class="form-control" type="text" placeholder="">
                            <span class="form-text text-muted"></span>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-md btn-tall btn-wide kt-font-bold kt-font-transform-u" data-dismiss="modal">取消</button>
                <a href="#" data-action="submit" class="btn btn-success btn-md btn-tall btn-wide kt-font-bold kt-font-transform-u">提交</a>
            </div>
        </div>
    </div>
</div>

src/Web/WebMVC/Views/ManualCode/_UpdateQuotaLimitModal.cshtml
<div id="modal__update_qrcode_quota" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">更新额度设定</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                </button>
            </div>
            <div class="modal-body">
                <form id="form_update_qrcode_quota" asp-controller="ManualCode" asp-action="UpdateQrCodeQuota" class="kt-form" method="post">
                    <div class="form-group">
                        <label for="userId" class="form-control-label">二维码编号 :</label>
                        <input type="text" class="form-control" name="qrcodeid" readonly>
                    </div>

                    <div class="form-group row">
                        <div class="col-lg-6">
                            <label class="">单日限额:</label>
                            <div class="input-group">
                                <input class="form-control" placeholder="" value="5000" name="DailyAmountLimit">
                                <div class="input-group-append"><span class="input-group-text">¥</span></div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-lg-6">
                            <label class="">单笔限额:</label>
                            <div class="input-group">
                                <div class="input-group-prepend"><span class="input-group-text">最低</span></div>
                                <input class="form-control" placeholder="" value="1" name="OrderAmountLowerLimit">
                                <div class="input-group-append"><span class="input-group-text">¥</span></div>

                            </div>
                        </div>
                        <div class="col-lg-6">
                            <label class="">&nbsp;</label>
                            <div class="input-group">
                                <div class="input-group-prepend"><span class="input-group-text">最高</span></div>
                                <input class="form-control" placeholder="" value="3000" id="update_qrcode_quota_order_amount_upper_limit" name="OrderAmountUpperLimit">
                                <div class="input-group-append"><span class="input-group-text">¥</span></div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-md btn-tall btn-wide kt-font-bold kt-font-transform-u" data-dismiss="modal">取消</button>
                <a href="#" data-action="submit" class="btn btn-success btn-md btn-tall btn-wide kt-font-bold kt-font-transform-u">提交</a>
            </div>
        </div>
    </div>
</div>

src/Web/WebMVC/Views/ManualCode/_UpdateTransactionCodeModal.cshtml
@model WebMVC.ViewModels.ManualCodeViewModels.IndexViewModel
@using WebMVC.Models
<div id="modal__update_transaction_qrcode_data" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">更新二维码数据</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                </button>
            </div>
            <div class="modal-body">
                <form id="form_update_transaction_qrcode_data" asp-controller="ManualCode" asp-action="UpdateTransactionCode" class="kt-form" method="post">
                    <div class="form-group">
                        <label for="userId" class="form-control-label">二维码编号 :</label>
                        <input type="text" class="form-control" name="qrcodeid" readonly>
                    </div>
                    <div class="form-group">
                        <label class="">支付宝用户ID</label>
                        <div>
                            <input name="alipayuserid" class="form-control" type="text" placeholder="">
                            <span class="form-text text-muted">扫描下方 QR Code 获取支付宝用户ID后填入上方栏位</span>
                            <img src="@Model.GetAlipayUserIdQrCodeData" alt="" style="height:150px;width:150px" />
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-md btn-tall btn-wide kt-font-bold kt-font-transform-u" data-dismiss="modal">取消</button>
                <a href="#" data-action="submit" class="btn btn-success btn-md btn-tall btn-wide kt-font-bold kt-font-transform-u">提交</a>
            </div>
        </div>
    </div>
</div>