src/Web/WebMVC/ViewModels/SystemConfigurationViewModels/PaymentChannelViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebMVC.ViewModels.SystemConfigurationViewModels
{
    public class PaymentChannelViewModel
    {
        public IEnumerable<SelectListItem> OpenFromInHours { get; set; }
        public IEnumerable<SelectListItem> OpenFromInMinutes { get; set; }
        public IEnumerable<SelectListItem> OpenToInHours { get; set; }
        public IEnumerable<SelectListItem> OpenToInMinutes { get; set; }

        [Required]
        public string OpenFromInHour { get; set; }

        [Required]
        public string OpenFromInMinute { get; set; }

        [Required]
        public string OpenToInHour { get; set; }

        [Required]
        public string OpenToInMinute { get; set; }

        [Required]
        public bool AutoToggle { get; set; }
    }
}

src/Web/WebMVC/ViewModels/SystemConfigurationViewModels/PaymentViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebMVC.ViewModels.SystemConfigurationViewModels
{
    public class PaymentViewModel
    {
        [Required]
        [Range(1, 600, ErrorMessage = "支付超时时间需介于 1 秒至 600 秒之间")]
        public int PaymentTimeoutInSecond { get; set; }

        [Required]
        [Range(1, 60000, ErrorMessage = "抢卖倒计时需介于 1 秒至 60000 秒之间")]
        public int SellRequestCountdownInSecond { get; set; }


        [Required]
        [Range(0, 9999, ErrorMessage = "Please enter valid integer Number")]
        public int SecondsBeforePayment { get; set; }

        [Required]
        public bool IsAmountUnchangeable { get; set; }

        [Required]
        public bool IsAccountUnchangeable { get; set; }

        [Required]
        public bool IsH5RedirectByScanEnabled { get; set; }

        [Required]
        public bool IsH5RedirectByClickEnabled { get; set; }

        [Required]
        public bool IsH5RedirectByPickingPhotoEnabled { get; set; }
    }
}

src/Web/WebMVC/ViewModels/SystemConfigurationViewModels/SiteBaseInfoViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebMVC.ViewModels.SystemConfigurationViewModels
{
    public class SiteBaseInfoViewModel
    {
        [Required]
        [StringLength(50, MinimumLength = 1)]
        public string SiteTitle { get; set; }

        [Required]
        [StringLength(50, MinimumLength = 1)]
        public string ContactAddress { get; set; }

        [Required]
        [StringLength(50, MinimumLength = 1)]
        public string ContactEmail { get; set; }

        [Required]
        [StringLength(50, MinimumLength = 1)]
        public string ConsumerHotline { get; set; }

        [Required]
        [StringLength(50, MinimumLength = 1)]
        public string ConsumerServiceQQ { get; set; }

        [Required]
        [StringLength(50, MinimumLength = 1)]
        public string ConsumerServiceSkype { get; set; }

        public IEnumerable<SelectListItem> BusinessHoursFroms { get; set; }
        public IEnumerable<SelectListItem> BusinessMinutesFroms { get; set; }
        public IEnumerable<SelectListItem> BusinessHoursTos { get; set; }
        public IEnumerable<SelectListItem> BusinessMinutesTos { get; set; }

        [Required]
        [Range(0, 23, ErrorMessage = "请输入正确的开始营业时间")]
        public string BusinessHoursFrom { get; set; }

        [Required]
        [Range(0, 59, ErrorMessage = "请输入正确的开始营业时间")]
        public string BusinessMinutesFrom { get; set; }

        [Required]
        [Range(0, 23, ErrorMessage = "请输入正确的结束营业时间")]
        public string BusinessHoursTo { get; set; }

        [Required]
        [Range(0, 59, ErrorMessage = "请输入正确的结束营业时间")]
        public string BusinessMinutesTo { get; set; }
    }
}

src/Web/WebMVC/ViewModels/SystemConfigurationViewModels/SystemNotificationSoundViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebMVC.ViewModels.SystemConfigurationViewModels
{
    public class SystemNotificationSoundViewModel
    {
        [Required]
        public bool Withdraw { get; set; }

        [Required]
        public bool Deposit { get; set; }

        [Required]
        public bool Member { get; set; }

        [Required]
        public bool QrCode { get; set; }

        [Required]
        public bool NewOrder { get; set; }

        [Required]
        public bool OrderTimeout { get; set; }
    }
}

src/Web/WebMVC/ViewModels/SystemConfigurationViewModels/UserNotificationViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebMVC.ViewModels.SystemConfigurationViewModels
{
    public class UserNotificationViewModel
    {
        [Required]
        public bool OrderTimeout { get; set; }

        [Required]
        public bool SuccessDeposit { get; set; }
    }
}

src/Web/WebMVC/ViewModels/SystemConfigurationViewModels/WithdrawalAndDepositViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebMVC.ViewModels.SystemConfigurationViewModels
{
    public class WithdrawalAndDepositViewModel
    {
        [Required]
        [Range(0, int.MaxValue, ErrorMessage = "最高单笔额度须为正整数")]
        public int EachAmountUpperLimit { get; set; }

        [Required]
        [Range(0, int.MaxValue, ErrorMessage = "最低单笔额度须为正整数")]
        public int EachAmountLowerLimit { get; set; }

        [Required]
        [Range(0, int.MaxValue, ErrorMessage = "单日限额须为正整数")]
        public int DailyAmountLimit { get; set; }

        [Required]
        [Range(0, int.MaxValue, ErrorMessage = "单日次数须为正整数")]
        public int DailyFrequencyLimit { get; set; }

        [Required]
        [Range(0, 1000, ErrorMessage = "提现手续费需介于 千分之1 至 千分之999 之间")]
        public int CommissionInThousandth { get; set; }


        public IEnumerable<SelectListItem> WithdrawalOpenFromInHours { get; set; }
        public IEnumerable<SelectListItem> WithdrawalOpenFromInMinutes { get; set; }
        public IEnumerable<SelectListItem> WithdrawalOpenToInHours { get; set; }
        public IEnumerable<SelectListItem> WithdrawalOpenToInMinutes { get; set; }

        public IEnumerable<SelectListItem> DepositOpenFromInHours { get; set; }
        public IEnumerable<SelectListItem> DepositOpenFromInMinutes { get; set; }
        public IEnumerable<SelectListItem> DepositOpenToInHours { get; set; }
        public IEnumerable<SelectListItem> DepositOpenToInMinutes { get; set; }


        [Required]
        public string WithdrawalOpenFromInHour { get; set; }

        [Required]
        public string WithdrawalOpenFromInMinute { get; set; }

        [Required]
        public string WithdrawalOpenToInHour { get; set; }

        [Required]
        public string WithdrawalOpenToInMinute { get; set; }

        [Required]
        public string DepositOpenFromInHour { get; set; }

        [Required]
        public string DepositOpenFromInMinute { get; set; }

        [Required]
        public string DepositOpenToInHour { get; set; }

        [Required]
        public string DepositOpenToInMinute { get; set; }
    }
}

src/Web/WebMVC/Controllers/SystemConfigurationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebMVC.Infrastructure.Services;
using WebMVC.Models.Permissions;
using WebMVC.ViewModels.SystemConfigurationViewModels;

namespace WebMVC.Controllers
{
    [Authorize]
    public class SystemConfigurationController : Controller
    {
        private readonly ISystemConfigurationService _systemConfigurationService;

        public SystemConfigurationController(ISystemConfigurationService systemConfigurationService)
        {
            _systemConfigurationService = systemConfigurationService ?? throw new ArgumentNullException(nameof(systemConfigurationService));
        }


        // GET: SystemConfiguration
        public ActionResult Index()
        {
            return View();
        }


        [Authorize(Policy = Permissions.SystemConfiguration.SiteBaseInfo.View)]
        [HttpGet]
        public IActionResult SiteBaseInfo()
        {
            var settings = _systemConfigurationService.GetSiteInfoAsync();

            TimeSpan businessHoursFrom = TimeSpan.Parse(settings.BusinessHoursFrom);
            TimeSpan businessHoursTo = TimeSpan.Parse(settings.BusinessHoursTo);

            var vm = new SiteBaseInfoViewModel()
            {
                SiteTitle = settings.SiteTitle,
                ContactAddress = settings.ContactAddress,
                ContactEmail = settings.ContactEmail,
                ConsumerHotline = settings.ConsumerHotline,
                ConsumerServiceQQ = settings.ConsumerServiceQQ,
                ConsumerServiceSkype = settings.ConsumerServiceSkype,
                BusinessHoursFroms = _systemConfigurationService.GetDateTimeSelectList(isHour: true, selectedItemValue: businessHoursFrom.Hours),
                BusinessMinutesFroms = _systemConfigurationService.GetDateTimeSelectList(isMinute: true, selectedItemValue: businessHoursFrom.Minutes),
                BusinessHoursTos = _systemConfigurationService.GetDateTimeSelectList(isHour: true, selectedItemValue: businessHoursTo.Hours),
                BusinessMinutesTos = _systemConfigurationService.GetDateTimeSelectList(isMinute: true, selectedItemValue: businessHoursTo.Minutes),
                BusinessHoursFrom = businessHoursFrom.ToString(@"hh"),
                BusinessMinutesFrom = businessHoursFrom.ToString(@"mm"),
                BusinessHoursTo = businessHoursTo.ToString(@"hh"),
                BusinessMinutesTo = businessHoursTo.ToString(@"mm"),
            };

            //ViewBag.BasketInoperativeMsg = errorMsg;

            return View(vm);
        }


        [Authorize(Policy = Permissions.SystemConfiguration.SiteBaseInfo.Edit)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SiteBaseInfo([FromForm]SiteBaseInfoViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest("无效参数。");
            }
            try
            {

                var baseInfoSettings = new SiteBaseInfo
                {
                    SiteTitle = vm.SiteTitle,
                    ContactAddress = vm.ContactAddress,
                    ContactEmail = vm.ContactEmail,
                    ConsumerHotline = vm.ConsumerHotline,
                    ConsumerServiceQQ = vm.ConsumerServiceQQ,
                    ConsumerServiceSkype = vm.ConsumerServiceSkype,
                    BusinessHoursFrom = vm.BusinessHoursFrom + ":" + vm.BusinessMinutesFrom,
                    BusinessHoursTo = vm.BusinessHoursTo + ":" + vm.BusinessMinutesTo
                };

                _systemConfigurationService.UpdateSiteBaseInfo(baseInfoSettings);
                return Ok(new { success = true });
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }


        }


        [Authorize(Policy = Permissions.SystemConfiguration.Payment.View)]
        [HttpGet]
        public IActionResult Payment()
        {
            var settings = _systemConfigurationService.GetPaymentAsync();


            var vm = new PaymentViewModel()
            {
                PaymentTimeoutInSecond = settings.PaymentTimeoutInSecond,
                SellRequestCountdownInSecond = settings.SellRequestCountdownInSecond,
                SecondsBeforePayment = settings.AlipayPaymentTemplate.SecondsBeforePayment,
                IsAmountUnchangeable = settings.AlipayPaymentTemplate.IsAmountUnchangeable,
                IsAccountUnchangeable = settings.AlipayPaymentTemplate.IsAccountUnchangeable,
                IsH5RedirectByScanEnabled = settings.AlipayPaymentTemplate.IsH5RedirectByScanEnabled,
                IsH5RedirectByClickEnabled = settings.AlipayPaymentTemplate.IsH5RedirectByClickEnabled,
                IsH5RedirectByPickingPhotoEnabled = settings.AlipayPaymentTemplate.IsH5RedirectByPickingPhotoEnabled
            };

            //ViewBag.BasketInoperativeMsg = errorMsg;

            return View(vm);
        }


        [Authorize(Policy = Permissions.SystemConfiguration.Payment.Edit)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Payment([FromForm]PaymentViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest("无效参数");
            }
            try
            {
                var settings = new Payment
                {
                    PaymentTimeoutInSecond = vm.PaymentTimeoutInSecond,
                    SellRequestCountdownInSecond = vm.SellRequestCountdownInSecond,
                    AlipayPaymentTemplate = new AlipayPaymentTemplate
                    {
                        SecondsBeforePayment = vm.SecondsBeforePayment,
                        IsAmountUnchangeable = vm.IsAmountUnchangeable,
                        IsAccountUnchangeable = vm.IsAccountUnchangeable,
                        IsH5RedirectByScanEnabled = vm.IsH5RedirectByScanEnabled,
                        IsH5RedirectByClickEnabled = vm.IsH5RedirectByClickEnabled,
                        IsH5RedirectByPickingPhotoEnabled = vm.IsH5RedirectByPickingPhotoEnabled,
                    }
                };

                _systemConfigurationService.UpdatePayment(settings);

                return Ok(new { success = true });
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }


        [Authorize(Policy = Permissions.SystemConfiguration.SystemNotificationSound.View)]
        [HttpGet]
        public IActionResult SystemNotificationSound()
        {
            var settings = _systemConfigurationService.GetSystemNotificationSoundAsync();


            var vm = new SystemNotificationSoundViewModel()
            {
                Withdraw = settings.Withdraw,
                Deposit = settings.Deposit,
                Member = settings.Member,
                QrCode = settings.QrCode,
                NewOrder = settings.NewOrder,
                OrderTimeout = settings.OrderTimeout
            };

            //ViewBag.BasketInoperativeMsg = errorMsg;

            return View(vm);
        }


        [Authorize(Policy = Permissions.SystemConfiguration.SystemNotificationSound.Edit)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SystemNotificationSound([FromForm]SystemNotificationSoundViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest("Invalid Request Params.");
            }
            try
            {

                var settings = new SystemNotificationSound
                {
                    Withdraw = vm.Withdraw,
                    Deposit = vm.Deposit,
                    Member = vm.Member,
                    QrCode = vm.QrCode,
                    NewOrder = vm.NewOrder,
                    OrderTimeout = vm.OrderTimeout
                };

                _systemConfigurationService.UpdateSystemNotificationSound(settings);

                return Ok(new { success = true });
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }


        [Authorize(Policy = Permissions.SystemConfiguration.UserNotification.View)]
        [HttpGet]
        public IActionResult UserNotification()
        {
            var settings = _systemConfigurationService.GetUserNotificationAsync();


            var vm = new UserNotificationViewModel()
            {
                OrderTimeout = settings.OrderTimeout,
                SuccessDeposit = settings.SuccessDeposit
            };

            //ViewBag.BasketInoperativeMsg = errorMsg;

            return View(vm);
        }


        [Authorize(Policy = Permissions.SystemConfiguration.UserNotification.Edit)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UserNotification([FromForm]UserNotificationViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest("Invalid Request Params.");
            }
            try
            {

                var settings = new UserNotification
                {
                    OrderTimeout = vm.OrderTimeout,
                    SuccessDeposit = vm.SuccessDeposit
                };

                _systemConfigurationService.UpdateUserNotification(settings);

                return Ok(new { success = true });
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }


        [Authorize(Policy = Permissions.SystemConfiguration.WithdrawalAndDeposit.View)]
        [HttpGet]
        public IActionResult WithdrawalAndDeposit()
        {
            var settings = _systemConfigurationService.GetWithdrawalAndDepositAsync();

src/Web/WebMVC/Views/SystemConfiguration/Payment.cshtml
@model WebMVC.ViewModels.SystemConfigurationViewModels.PaymentViewModel

@{
    ViewData["Title"] = "Payment";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}


<div class="kt-content  kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor" id="kt_content">

    <!-- begin:: Content Head -->
    <div class="kt-subheader   kt-grid__item" id="kt_subheader">
        <div class="kt-container  kt-container--fluid ">
            <div class="kt-subheader__main">
                <h3 class="kt-subheader__title">
                    支付
                </h3>
                <span class="kt-subheader__separator kt-subheader__separator--v"></span>
                <div class="kt-subheader__group" id="kt_subheader_search">
                    <span class="kt-subheader__desc" id="kt_subheader_total">
                        支付相关设置
                    </span>
                </div>
            </div>
            <div class="kt-subheader__toolbar">
                <a href="#" class="btn btn-default btn-bold" onclick="ReturnPreviousPage()">
                    返回
                </a>
            </div>
        </div>
    </div>

    <!-- end:: Content Head -->
    <!-- begin:: Content -->
    <div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">

        <!--Begin:: Portlet-->
        <div class="kt-portlet kt-portlet--tabs">
            <div class="kt-portlet__head">
                <div class="kt-portlet__head-toolbar">
                    <ul class="nav nav-tabs nav-tabs-space-lg nav-tabs-line nav-tabs-bold nav-tabs-line-3x nav-tabs-line-brand" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" data-toggle="tab" href="#kt_apps_contacts_view_tab_2" role="tab">
                                <i class="flaticon2-calendar-3"></i> 支付设置
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="kt-portlet__body">
                <div class="tab-content  kt-margin-t-20">

                    <!--Begin:: Tab Content-->
                    <div class="tab-pane active" id="kt_apps_contacts_view_tab_2" role="tabpanel">
                        <form asp-controller="SystemConfiguration" asp-action="Payment" id="kt_system_payment_form" class="kt-form kt-form--label-right" method="post">
                            <div class="kt-form__body">
                                <div class="kt-section kt-section--first">
                                    <div class="kt-section__body">
                                        <div class="form-group row">
                                            <label class="col-xl-3 col-lg-3 col-form-label">支付页面超时时间</label>
                                            <div class="col-sm-3 col-sm-offset-3">
                                                <div class="input-group">
                                                    <input asp-for="PaymentTimeoutInSecond" class="form-control" type="text" value="@Model.PaymentTimeoutInSecond" name="paymenttimeoutinsecond">
                                                    <div class="input-group-append"><span class="input-group-text">秒</span></div>&emsp;&emsp;
                                                </div>
                                                <span class="form-text text-muted">可设置值介于1秒至600秒间</span>

                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-xl-3 col-lg-3 col-form-label">抢卖倒计时</label>
                                            <div class="col-sm-3 col-sm-offset-3">
                                                <div class="input-group">
                                                    <input asp-for="SellRequestCountdownInSecond" class="form-control" type="text" value="@Model.SellRequestCountdownInSecond" name="sellrequestcountdowninsecond">
                                                    <div class="input-group-append"><span class="input-group-text">秒</span></div>&emsp;&emsp;
                                                </div>
                                                <span class="form-text text-muted">可设置值介于1秒至60000秒间</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="kt-separator kt-separator--space-lg kt-separator--fit kt-separator--border-solid"></div>
                                <div class="kt-form__actions">
                                    <div class="row">
                                        <div class="col-xl-3"></div>
                                        <div class="col-lg-9 col-xl-6">
                                            <a class="btn btn-brand btn-bold text-white" data-ktwizard-type="action-submit">提交</a>
                                            <a href="#" class="btn btn-clean btn-bold" onclick="ReturnPreviousPage()">取消</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>

                    <!--End:: Tab Content-->
                </div>
            </div>
        </div>

        <!--End:: Portlet-->
    </div>

    <!-- end:: Content -->
</div>


@section Scripts{
    <script src="~/js/pages/system-configuration/edit-payment.js" type="text/javascript"></script>
}

src/Web/WebMVC/Views/SystemConfiguration/PaymentChannel.cshtml
@model WebMVC.ViewModels.SystemConfigurationViewModels.PaymentChannelViewModel

@{
    ViewData["Title"] = "PaymentChannel";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}


<div class="kt-content  kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor" id="kt_content">

    <!-- begin:: Content Head -->
    <div class="kt-subheader   kt-grid__item" id="kt_subheader">
        <div class="kt-container  kt-container--fluid ">
            <div class="kt-subheader__main">
                <h3 class="kt-subheader__title">
                    通道开放时间
                </h3>
                <span class="kt-subheader__separator kt-subheader__separator--v"></span>
                <div class="kt-subheader__group" id="kt_subheader_search">
                    <span class="kt-subheader__desc" id="kt_subheader_total">
                        设置平台的提单时间
                    </span>
                </div>
            </div>
            <div class="kt-subheader__toolbar">
                <a href="#" class="btn btn-default btn-bold" onclick="ReturnPreviousPage()">
                    返回
                </a>
            </div>
        </div>
    </div>

    <!-- end:: Content Head -->
    <!-- begin:: Content -->
    <div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">

        <!--Begin:: Portlet-->
        <div class="kt-portlet kt-portlet--tabs">
            <div class="kt-portlet__head">
                <div class="kt-portlet__head-toolbar">
                    <ul class="nav nav-tabs nav-tabs-space-lg nav-tabs-line nav-tabs-bold nav-tabs-line-3x nav-tabs-line-brand" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" data-toggle="tab" href="#kt_apps_contacts_view_tab_2" role="tab">
                                <i class="flaticon2-calendar-3"></i> 开放时间
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="kt-portlet__body">
                <div class="tab-content  kt-margin-t-20">

                    <!--Begin:: Tab Content-->
                    <div class="tab-pane active" id="kt_apps_contacts_view_tab_2" role="tabpanel">
                        <form asp-controller="SystemConfiguration" asp-action="PaymentChannel" id="kt_system_paymentchannel_form" class="kt-form kt-form--label-right" method="post">
                            <div class="kt-form__body">
                                <div class="kt-section kt-section--first">
                                    <div class="kt-section__body">

                                        <div class="row">
                                            <label class="col-xl-3"></label>
                                            <div class="col-lg-9 col-xl-6">
                                                <h3 class="kt-section__title kt-section__title-sm">开放提单时间:</h3>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-xl-3 col-lg-3 col-form-label">开始</label>
                                            <div class="col-sm-3 col-sm-offset-3">
                                                <div class="input-group">
                                                    <select asp-for="OpenFromInHour" asp-items="@Model.OpenFromInHours" name="openfrominhour" class="form-control form-control--fixed kt-selectpicker" data-size="6" data-live-search="true">
                                                    </select>
                                                    <div class="input-group-append"><span class="input-group-text">点</span></div>&emsp;&emsp;

                                                    <select asp-for="OpenFromInMinute" asp-items="@Model.OpenFromInMinutes" name="openfrominminute" class="form-control form-control--fixed kt-selectpicker" data-size="6" data-live-search="true">
                                                    </select>
                                                    <div class="input-group-append"><span class="input-group-text">分</span></div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-xl-3 col-lg-3 col-form-label">结束</label>
                                            <div class="col-sm-3 col-sm-offset-3">
                                                <div class="input-group">
                                                    <select asp-for="OpenToInHour" asp-items="@Model.OpenToInHours" name="opentoinhour" class="form-control form-control--fixed kt-selectpicker" data-size="6" data-live-search="true">
                                                    </select>
                                                    <div class="input-group-append"><span class="input-group-text">点</span></div>&emsp;&emsp;

                                                    <select asp-for="OpenToInMinute" asp-items="@Model.OpenToInMinutes" name="opentoinminute" class="form-control form-control--fixed kt-selectpicker" data-size="6" data-live-search="true">
                                                    </select>
                                                    <div class="input-group-append"><span class="input-group-text">分</span></div>
                                                </div>
                                                <span class="form-text text-muted">商户将无法在开放时间外提单</span>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <label class="col-xl-3"></label>
                                        <div class="col-lg-9 col-xl-6">
                                            <h3 class="kt-section__title kt-section__title-sm">自动化:</h3>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-3 col-form-label">自动停用商户</label>
                                        <div class="col-3">
                                            <span class="kt-switch kt-switch--outline kt-switch--icon kt-switch--success">
                                                <label>
                                                    <input asp-for="AutoToggle" type="checkbox" name="autotoggle">
                                                    <span></span>
                                                </label>
                                            </span>
                                            <span class="form-text text-muted">现在时间超过开放时间时自动停用所有商户。</span>
                                        </div>
                                    </div>
                                </div>
                    </div>
                    <div class="kt-separator kt-separator--space-lg kt-separator--fit kt-separator--border-solid"></div>
                    <div class="kt-form__actions">
                        <div class="row">
                            <div class="col-xl-3"></div>
                            <div class="col-lg-9 col-xl-6">
                                <a class="btn btn-brand btn-bold text-white" data-ktwizard-type="action-submit">提交</a>
                                <a href="#" class="btn btn-clean btn-bold" onclick="ReturnPreviousPage()">取消</a>
                            </div>
                        </div>
                    </div>
                    </form>
                </div>

                <!--End:: Tab Content-->
            </div>
        </div>
    </div>

    <!--End:: Portlet-->
</div>

<!-- end:: Content -->
</div>


@section Scripts{
    <script src="~/js/pages/system-configuration/edit-paymentchannel.js" type="text/javascript"></script>

    <script src="~/lib/metronic/dist/assets/js/pages/crud/forms/widgets/bootstrap-select.js" type="text/javascript"></script>
}